version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: chat_db
    ports:
      - "3307:3306"

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:yourpassword@mysql:3306/chat_db"
    entrypoint: ["./wait-for-it.sh", "mysql", "--", "python", "app.py"]
